version: "3.1"

services:
  db:
    image: mysql:8.0.27
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
